// Dados estáticos do Bingo Literário: 4 temas x 50 desafios cada.
// Gerado a partir da lista fornecida pelo usuário. Não editar os textos
// sem atualizar também o histórico já sorteado (o índice de cada desafio
// dentro do tema é o que fica salvo no Supabase, então a ORDEM importa).
const BINGO_TEMAS = [
  {
    id: 'mundo',
    nome: 'Mundo e Culturas',
    icone: 'fa-earth-americas',
    cor: '#4A7C59',
    desafios: [
      'Autor brasileiro',
      'Autor argentino',
      'Autor colombiano',
      'Autor chileno',
      'Autor mexicano',
      'Autor português',
      'Autor espanhol',
      'Autor francês',
      'Autor italiano',
      'Autor alemão',
      'Autor russo',
      'Autor inglês',
      'Autor irlandês',
      'Autor norte-americano',
      'Autor canadense',
      'Autor japonês',
      'Autor chinês',
      'Autor indiano',
      'Autor sul-coreano',
      'Autor de outro país asiático',
      'Autor nigeriano',
      'Autor sul-africano',
      'Autor de outro país africano',
      'Autor australiano',
      'Autor neozelandês',
      'Livro ambientado na América do Sul',
      'Livro ambientado na América do Norte',
      'Livro ambientado na Europa',
      'Livro ambientado na Ásia',
      'Livro ambientado na África',
      'Livro ambientado na Oceania',
      'Livro escrito originalmente em espanhol',
      'Livro escrito originalmente em francês',
      'Livro escrito originalmente em italiano',
      'Livro escrito originalmente em alemão',
      'Livro escrito originalmente em russo',
      'Livro escrito originalmente em inglês',
      'Livro escrito originalmente em japonês',
      'Livro escrito originalmente em outro idioma que você nunca leu',
      'Livro de um país cuja literatura você nunca experimentou',
      'Livro de um autor de origem indígena',
      'Livro que apresente uma cultura muito diferente da sua',
      'Livro ambientado em um país que você gostaria de visitar',
      'Livro ambientado em uma cidade que você gostaria de conhecer',
      'Livro que atravesse mais de um país',
      'Livro escrito por um imigrante ou expatriado',
      'Livro traduzido diretamente de um idioma que você não conhece',
      'Dois livros de continentes diferentes sobre tema semelhante',
      'Três autores de três países diferentes no mesmo mês',
      'Livro de um país que você consiga localizar no mapa, mas nunca havia lido autor algum',
    ]
  },
  {
    id: 'calhambacos',
    nome: 'Calhambaços e Desafios',
    icone: 'fa-book-atlas',
    cor: '#B5651D',
    desafios: [
      'Livro com menos de 100 páginas',
      'Livro com 100–200 páginas',
      'Livro com 200–300 páginas',
      'Livro com mais de 300 páginas',
      'Livro com mais de 400 páginas',
      'Livro com mais de 500 páginas',
      'Livro com mais de 600 páginas',
      'Livro com mais de 700 páginas',
      'Livro com mais de 800 páginas',
      'Livro com mais de 900 páginas',
      'Livro com mais de 1.000 páginas',
      'Livro com mais de 1.200 páginas',
      'Livro com mais de 1.500 páginas',
      'Livro com mais de 2.000 páginas',
      'Livro que tenha mais de 500 páginas e termine em menos de 15 dias',
      'Livro que leve mais de um mês para terminar',
      'Livro que você tenha medo de começar por ser muito grande',
      'Livro que você tenha abandonado anteriormente',
      'Livro que você considere difícil',
      'Livro escrito em mais de um volume',
      'Série de três livros ou mais',
      'Primeiro volume de uma série muito longa',
      'Último volume de uma série',
      'Livro com mais de 100 capítulos',
      'Livro com capítulos extremamente longos',
      'Livro com capítulos extremamente curtos',
      'Livro com estrutura narrativa incomum',
      'Livro com múltiplos narradores',
      'Livro contado em primeira pessoa',
      'Livro contado em terceira pessoa',
      'Livro com narrativa não linear',
      'Livro com histórias dentro de histórias',
      'Livro com vários personagens principais',
      'Livro que atravesse várias décadas',
      'Livro que atravesse várias gerações',
      'Livro que atravesse mais de um século',
      'Livro publicado originalmente em dois ou mais volumes',
      'Livro que tenha uma edição comentada',
      'Livro cuja introdução tenha mais de 20 páginas',
      'Livro cuja leitura exija consultar notas ou referências',
      'Livro que você precise pesquisar enquanto lê',
      'Livro que demore mais de 20 horas para ler',
      'Livro com mais páginas do que você já leu em um único mês',
      'Livro mais longo da sua estante',
      'Livro mais longo que você já leu',
      'Livro que tenha mais de 1 kg',
      'Livro que ocupe mais de 5 cm na estante',
      'Livro que você termine apesar de pensar em abandoná-lo',
      'Ler dois calhamaços consecutivamente',
      'Ler um livro de 1.000+ páginas do início ao fim',
    ]
  },
  {
    id: 'classicos',
    nome: 'Clássicos e História',
    icone: 'fa-landmark',
    cor: '#6B4E71',
    desafios: [
      'Livro publicado antes de 1700',
      'Livro publicado no século XVIII',
      'Livro publicado entre 1800 e 1850',
      'Livro publicado entre 1851 e 1900',
      'Livro publicado entre 1901 e 1925',
      'Livro publicado entre 1926 e 1950',
      'Livro publicado entre 1951 e 1975',
      'Livro publicado entre 1976 e 2000',
      'Livro publicado depois de 2000',
      'Livro com mais de 100 anos',
      'Livro com mais de 200 anos',
      'Livro com mais de 300 anos',
      'Autor vencedor do Nobel de Literatura',
      'Autor indicado ao Nobel de Literatura',
      'Autor que morreu há mais de 100 anos',
      'Primeiro romance de um autor consagrado',
      'Último romance de um autor consagrado',
      'Obra mais famosa de um autor',
      'Obra menos conhecida de um autor famoso',
      'Três livros do mesmo autor',
      'Cinco livros do mesmo autor',
      'Livro que influenciou outros escritores',
      'Livro considerado um marco literário',
      'Livro considerado controverso em sua época',
      'Livro censurado ou proibido em algum contexto histórico',
      'Livro que tenha causado grande repercussão quando publicado',
      'Livro que tenha recebido adaptação cinematográfica',
      'Livro que tenha recebido várias adaptações',
      'Livro que tenha inspirado outras obras',
      'Obra de um autor que você nunca havia lido',
      'Clássico brasileiro',
      'Clássico latino-americano',
      'Clássico europeu',
      'Clássico norte-americano',
      'Clássico asiático',
      'Clássico africano',
      'Obra de um autor do século XIX',
      'Obra de um autor do século XX',
      'Obra de um autor contemporâneo',
      'Romance realista',
      'Romance romântico',
      'Obra modernista',
      'Obra de vanguarda',
      'Tragédia clássica',
      'Peça teatral consagrada',
      'Livro de contos clássico',
      'Livro de poesia clássico',
      'Ensaio clássico',
      'Livro que esteja em uma lista de grandes clássicos da literatura',
      'Livro que você considera que deveria ter lido há muito tempo',
    ]
  },
  {
    id: 'fora',
    nome: 'Fora da Zona de Conforto',
    icone: 'fa-dice',
    cor: '#C1440E',
    desafios: [
      'Ler um gênero que você normalmente evita',
      'Ler poesia',
      'Ler teatro',
      'Ler ensaio',
      'Ler biografia',
      'Ler autobiografia',
      'Ler memórias',
      'Ler ficção científica',
      'Ler fantasia',
      'Ler terror',
      'Ler romance policial',
      'Ler distopia',
      'Ler sátira',
      'Ler literatura de viagem',
      'Ler um livro epistolar',
      'Ler um livro experimental',
      'Ler um livro em que o narrador não seja confiável',
      'Ler um livro sem protagonista tradicional',
      'Ler um livro sem romance amoroso',
      'Ler um livro cujo protagonista seja uma criança',
      'Ler um livro cujo protagonista seja idoso',
      'Ler um livro narrado por uma mulher',
      'Ler um livro narrado por várias pessoas',
      'Ler um livro narrado em primeira pessoa',
      'Ler um livro narrado em segunda pessoa',
      'Ler um livro que se passe quase inteiramente em um único lugar',
      'Ler um livro que aconteça durante apenas um dia',
      'Ler um livro que atravesse várias gerações',
      'Ler um livro sem pesquisar absolutamente nada antes',
      'Ler um livro escolhido pela capa',
      'Ler um livro escolhido pelo título',
      'Ler um livro escolhido aleatoriamente da estante',
      'Ler o livro mais antigo que você possui e ainda não leu',
      'Ler um livro comprado há mais de cinco anos',
      'Ler um livro recebido de presente',
      'Ler um livro indicado por outra pessoa',
      'Ler um livro escolhido por sorteio',
      'Ler um livro que você abandonou',
      'Ler um livro que você já leu e não gostou',
      'Reler um livro favorito',
      'Ler um livro sabendo apenas o título e o autor',
      'Ler um livro sem consultar avaliações antes',
      'Ler um livro que você espera não gostar',
      'Ler um livro que esteja fora do seu gênero habitual',
      'Ler um livro que você normalmente consideraria "difícil demais"',
      'Ler um livro que provoque uma discussão filosófica',
      'Ler um livro que faça você pesquisar um assunto desconhecido',
      'Ler um livro que mude sua percepção sobre determinado tema',
      'Ler um livro que permaneça na sua cabeça por vários dias',
      'Ler um livro que você escolha exclusivamente por curiosidade',
    ]
  },
];
